"""Phase 2 data layer — Jordanian football platform collections.

This module documents the shape of every MongoDB collection used by the
Jordanian football platform (Phase 2) and by the pre-existing TurfBook
booking stack (Phase 1). MongoDB has no server-side schema here, so the
document shapes below are the contract: route handlers and services MUST
validate against these shapes (see ``*_SCHEMA`` dicts) and indexes are
enforced by :func:`migrations.ensure_indexes`.

Conventions (shared with Phase 1):
- ``_id`` is ALWAYS a string uuid-hex generated by ``db.new_id()``
  (never an ObjectId).
- Timestamps are tz-aware UTC datetimes via ``db.now()``; use ``db.ser()``
  / ``db.ser_many()`` to serialize documents for JSON responses.
- Soft delete: entity collections carry ``deleted_at`` (None = alive).
  Reference/geography collections are hard-kept and deactivated with
  ``is_active`` instead.
- ``*_SCHEMA`` dicts describe ``required`` fields, ``fields`` (type /
  enum / foreign-key notes). They are documentation + a validation
  reference for services; they are NOT enforced by Mongo itself.

CROSS-COLLECTION INTEGRITY RULES (enforced in service code, not in Mongo):
1. ``standings`` / ``player_statistics`` / ``team_statistics`` are DERIVED
   aggregates. They may only be (re)calculated from ``matches`` with
   status FINISHED (or UNDER_REVIEW-resolved) via the recalc service.
   Never write them by hand from user input.
2. ``match_events`` are IMMUTABLE once the parent match reaches FINISHED.
   Corrections after FINISHED require the ``matches.result`` permission
   and must be written through the result-amendment flow (which re-runs
   the stats recalc and writes an ``audit_logs`` entry).
3. A ``match`` belongs to exactly one competition context: either
   (league_id + season_id [+ division_id]) or (tournament_id). Never both.
4. ``fixtures`` are schedule slots created by the fixture generator.
   A ``match`` created from a fixture MUST set ``match.fixture_id``;
   deleting/replacing a fixture must not orphan its match.
5. ``league_teams`` is the single source of truth for "team X plays in
   league Y season Z". ``standings`` rows are only created for teams
   present in ``league_teams`` with status APPROVED.
6. ``team_members`` (team_id, user_id) unique: a user has exactly one
   membership row per team; role changes update the row, they never add
   a second one. Deleting a team cascades (soft-deletes) its members,
   invitations and entries.
7. ``player_profiles.user_id`` is 1:1 with ``users._id``. A player row in
   a match lineup or event references the *user* id; display data comes
   from ``player_profiles``.
8. ``referee_assignments`` reference ``matches`` + ``referees``. A referee
   cannot be assigned twice to the same match in the same role
   (unique index), and assignments for a FINISHED match are frozen.
9. ``disputes`` targeting a match may only be OPENed while the match is
   not FINISHED, or within the protest window after FINISHED
   (``settings`` key ``match_protest_window_hours``).
10. ``push_subscriptions`` (user_id, endpoint) unique: re-subscribing the
    same browser endpoint updates the row, never duplicates it.
11. ``settings._id`` IS the setting key (e.g. ``"site_name"``) — upsert by
    key only.
12. Geography hierarchy: governorates -> cities -> areas. Teams, leagues,
    referees and facilities reference geography by *key* (stable slugs),
    never by denormalized names, so renames don't break references.
"""

# ---------------------------------------------------------------------------
# Collection registry
# ---------------------------------------------------------------------------

# Existing Phase-1 collections (registered here so every consumer uses one
# spelling; do not rename these).
EXISTING_COLLECTIONS = {
    "users": "users",
    "sessions": "sessions",
    "one_time_tokens": "one_time_tokens",
    "roles": "roles",
    "app_meta": "app_meta",
    "catalog": "catalog",
    "counters": "counters",
    "facilities": "facilities",
    "pitches": "pitches",
    "availability_blocks": "availability_blocks",
    "slot_reservations": "slot_reservations",
    "bookings": "bookings",
    "payments": "payments",
    "coupons": "coupons",
    "organization_members": "organization_members",
    "uploads": "uploads",
    "reviews": "reviews",
    "favorites": "favorites",
    "notifications": "notifications",
    "audit_logs": "audit_logs",
}

# New Phase-2 collections.
NEW_COLLECTIONS = {
    # geography
    "governorates": "governorates",
    "cities": "cities",
    "areas": "areas",
    # teams & players
    "teams": "teams",
    "team_members": "team_members",
    "team_invitations": "team_invitations",
    "player_profiles": "player_profiles",
    # leagues
    "leagues": "leagues",
    "seasons": "seasons",
    "divisions": "divisions",
    "league_teams": "league_teams",
    "fixtures": "fixtures",
    # matches
    "matches": "matches",
    "match_events": "match_events",
    "match_lineups": "match_lineups",
    "player_statistics": "player_statistics",
    "team_statistics": "team_statistics",
    "standings": "standings",
    # tournaments
    "tournaments": "tournaments",
    "tournament_groups": "tournament_groups",
    "tournament_rounds": "tournament_rounds",
    "tournament_entries": "tournament_entries",
    # officiating & disputes
    "disputes": "disputes",
    "referees": "referees",
    "referee_assignments": "referee_assignments",
    # content & messaging
    "news": "news",
    "announcements": "announcements",
    "push_subscriptions": "push_subscriptions",
    "notification_preferences": "notification_preferences",
    # platform
    "settings": "settings",
}

COLLECTIONS = {**EXISTING_COLLECTIONS, **NEW_COLLECTIONS}

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

MATCH_STATUS = (
    "SCHEDULED",
    "LIVE",
    "HALFTIME",
    "FINISHED",
    "POSTPONED",
    "CANCELLED",
    "UNDER_REVIEW",
)
"""Lifecycle of a match. LIVE/HALFTIME are set by the live-score flow;
UNDER_REVIEW freezes stats recalc until resolved to FINISHED or CANCELLED."""

# NOTE: no canonical BOOKING_STATUS constant existed in Phase 1 — booking
# statuses were inline string literals in routes_bookings. This tuple
# canonicalizes the literals actually in use; keep it in sync with
# routes_bookings if new states are added there. Do NOT define a second
# booking-status enum elsewhere.
BOOKING_STATUS = (
    "PENDING",
    "CONFIRMED",
    "CANCELLED",
    "COMPLETED",
    "NO_SHOW",
    "REJECTED",
    "EXPIRED",
)

LEAGUE_STATUS = (
    "DRAFT",
    "REGISTRATION",
    "ACTIVE",
    "PAUSED",
    "COMPLETED",
    "CANCELLED",
)
"""Used by leagues, seasons and tournaments alike."""

DISPUTE_STATUS = (
    "OPEN",
    "IN_REVIEW",
    "RESOLVED",
    "REJECTED",
    "ESCALATED",
)

DISPUTE_TYPE = (
    "MATCH_RESULT",
    "BOOKING",
    "PAYMENT",
    "CONDUCT",
    "OTHER",
)

PAYMENT_STATUS = (
    "PENDING",
    "PAID",
    "FAILED",
    "REFUNDED",
    "PARTIALLY_REFUNDED",
    "CANCELLED",
)
"""Canonicalizes the inline literals used in routes_bookings payments."""

TOURNAMENT_FORMAT = (
    "KNOCKOUT",
    "ROUND_ROBIN",
    "GROUPS_KNOCKOUT",
)

TEAM_MEMBER_ROLE = (
    "OWNER",
    "CAPTAIN",
    "PLAYER",
    "STAFF",
)

INVITATION_STATUS = (
    "PENDING",
    "ACCEPTED",
    "DECLINED",
    "EXPIRED",
    "CANCELLED",
)

LEAGUE_TEAM_STATUS = (
    "PENDING",
    "APPROVED",
    "REJECTED",
    "WITHDRAWN",
    "DISQUALIFIED",
)

MATCH_EVENT_TYPE = (
    "KICKOFF",
    "GOAL",
    "OWN_GOAL",
    "PENALTY_GOAL",
    "PENALTY_MISS",
    "ASSIST",
    "YELLOW_CARD",
    "SECOND_YELLOW",
    "RED_CARD",
    "SUBSTITUTION",
    "HALFTIME_WHISTLE",
    "FULLTIME_WHISTLE",
    "MATCH_POSTPONED",
    "MATCH_CANCELLED",
    "NOTE",
)

MATCH_PERIOD = (
    "1H",
    "2H",
    "ET1",
    "ET2",
    "PENS",
)

REFEREE_ASSIGNMENT_ROLE = (
    "MAIN",
    "ASSISTANT_1",
    "ASSISTANT_2",
    "FOURTH_OFFICIAL",
    "VAR",
)

REFEREE_ASSIGNMENT_STATUS = (
    "ASSIGNED",
    "CONFIRMED",
    "DECLINED",
    "COMPLETED",
)

PLAYER_POSITION = (
    "GK",
    "RB", "CB", "LB",
    "RWB", "LWB",
    "CDM", "CM", "CAM",
    "RM", "LM",
    "RW", "LW",
    "ST", "CF",
)

CONTENT_STATUS = (
    "DRAFT",
    "PUBLISHED",
    "ARCHIVED",
)

# ---------------------------------------------------------------------------
# Helper for schema docs
# ---------------------------------------------------------------------------


def _shape(description, required, fields):
    """Build a documented schema dict (documentation/validation reference)."""
    return {
        "description": description,
        "required": list(required),
        "fields": dict(fields),
    }

# ---------------------------------------------------------------------------
# Geography — governorates / cities / areas
# ---------------------------------------------------------------------------

GOVERNORATES_SCHEMA = _shape(
    "Jordan's 12 governorates. Seeded idempotently by seed.py; never seeded "
    "with fake data elsewhere. Reference by `key`.",
    ["key", "name_en", "name_ar"],
    {
        "_id": {"type": "str", "note": "uuid hex via new_id()"},
        "key": {"type": "str", "note": "stable slug, unique. e.g. 'amman', 'irbid', 'zarqa', 'balqa', 'mafraq', 'jarash', 'ajloun', 'madaba', 'karak', 'tafilah', 'maan', 'aqaba'"},
        "name_en": {"type": "str", "note": "e.g. 'Amman'"},
        "name_ar": {"type": "str", "note": "e.g. 'عمّان'"},
        "is_active": {"type": "bool", "note": "default True"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

CITIES_SCHEMA = _shape(
    "Cities/towns within a governorate. Child of governorates.",
    ["governorate_key", "key", "name_en", "name_ar"],
    {
        "_id": {"type": "str"},
        "governorate_key": {"type": "str", "ref": "governorates.key"},
        "key": {"type": "str", "note": "unique within governorate"},
        "name_en": {"type": "str"},
        "name_ar": {"type": "str"},
        "is_active": {"type": "bool", "note": "default True"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

AREAS_SCHEMA = _shape(
    "Districts/areas within a city. Child of cities.",
    ["governorate_key", "city_key", "key", "name_en", "name_ar"],
    {
        "_id": {"type": "str"},
        "governorate_key": {"type": "str", "ref": "governorates.key"},
        "city_key": {"type": "str", "ref": "cities.key"},
        "key": {"type": "str", "note": "unique within city"},
        "name_en": {"type": "str"},
        "name_ar": {"type": "str"},
        "is_active": {"type": "bool", "note": "default True"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

# ---------------------------------------------------------------------------
# Teams & players
# ---------------------------------------------------------------------------

TEAMS_SCHEMA = _shape(
    "Football teams. Slug is globally unique; soft-deleted via deleted_at.",
    ["name", "slug", "owner_id"],
    {
        "_id": {"type": "str"},
        "name": {"type": "str"},
        "name_ar": {"type": "str", "required": False},
        "slug": {"type": "str", "note": "URL slug, globally unique"},
        "short_name": {"type": "str", "required": False, "note": "3-letter code e.g. 'WAH'"},
        "logo_url": {"type": "str", "required": False},
        "colors": {"type": "dict", "required": False, "note": "{primary: hex, secondary: hex}"},
        "governorate_key": {"type": "str", "required": False, "ref": "governorates.key"},
        "city_key": {"type": "str", "required": False, "ref": "cities.key"},
        "owner_id": {"type": "str", "ref": "users._id"},
        "captain_id": {"type": "str", "required": False, "ref": "users._id"},
        "home_facility_id": {"type": "str", "required": False, "ref": "facilities._id"},
        "founded_year": {"type": "int", "required": False},
        "is_verified": {"type": "bool", "note": "default False; set by admins"},
        "is_active": {"type": "bool", "note": "default True"},
        "deleted_at": {"type": "datetime", "required": False},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

TEAM_MEMBERS_SCHEMA = _shape(
    "Team roster. (team_id, user_id) is unique — one row per user per team.",
    ["team_id", "user_id", "role"],
    {
        "_id": {"type": "str"},
        "team_id": {"type": "str", "ref": "teams._id"},
        "user_id": {"type": "str", "ref": "users._id"},
        "role": {"type": "str", "enum": "TEAM_MEMBER_ROLE"},
        "jersey_number": {"type": "int", "required": False},
        "position": {"type": "str", "required": False, "enum": "PLAYER_POSITION"},
        "joined_at": {"type": "datetime"},
        "is_active": {"type": "bool", "note": "default True; False = removed but history kept"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

TEAM_INVITATIONS_SCHEMA = _shape(
    "Pending invites to join a team. Token is single-use and expires.",
    ["team_id", "invited_by", "role", "token", "expires_at"],
    {
        "_id": {"type": "str"},
        "team_id": {"type": "str", "ref": "teams._id"},
        "invited_user_id": {"type": "str", "required": False, "ref": "users._id",
                            "note": "set when inviting an existing user"},
        "invited_email": {"type": "str", "required": False,
                          "note": "set when inviting by email; user may not exist yet"},
        "invited_by": {"type": "str", "ref": "users._id"},
        "role": {"type": "str", "enum": "TEAM_MEMBER_ROLE"},
        "status": {"type": "str", "enum": "INVITATION_STATUS", "note": "default PENDING"},
        "token": {"type": "str", "note": "unique single-use token"},
        "expires_at": {"type": "datetime"},
        "responded_at": {"type": "datetime", "required": False},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

PLAYER_PROFILES_SCHEMA = _shape(
    "Extended football profile for a user. 1:1 with users via user_id.",
    ["user_id", "display_name"],
    {
        "_id": {"type": "str"},
        "user_id": {"type": "str", "ref": "users._id", "note": "unique"},
        "display_name": {"type": "str"},
        "date_of_birth": {"type": "datetime", "required": False},
        "nationality": {"type": "str", "required": False, "note": "default 'JO'"},
        "position_primary": {"type": "str", "required": False, "enum": "PLAYER_POSITION"},
        "position_secondary": {"type": "str", "required": False, "enum": "PLAYER_POSITION"},
        "preferred_foot": {"type": "str", "required": False, "note": "LEFT | RIGHT | BOTH"},
        "height_cm": {"type": "int", "required": False},
        "weight_kg": {"type": "int", "required": False},
        "jersey_number": {"type": "int", "required": False},
        "governorate_key": {"type": "str", "required": False, "ref": "governorates.key"},
        "bio": {"type": "str", "required": False},
        "photo_url": {"type": "str", "required": False},
        "is_public": {"type": "bool", "note": "default True"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

# ---------------------------------------------------------------------------
# Leagues
# ---------------------------------------------------------------------------

LEAGUES_SCHEMA = _shape(
    "A football league/competition (e.g. Jordanian community league).",
    ["name", "slug", "organizer_id"],
    {
        "_id": {"type": "str"},
        "name": {"type": "str"},
        "name_ar": {"type": "str", "required": False},
        "slug": {"type": "str", "note": "globally unique"},
        "description": {"type": "str", "required": False},
        "logo_url": {"type": "str", "required": False},
        "cover_url": {"type": "str", "required": False},
        "status": {"type": "str", "enum": "LEAGUE_STATUS", "note": "default DRAFT"},
        "governorate_key": {"type": "str", "required": False, "ref": "governorates.key",
                            "note": "None = national"},
        "registration_fee": {"type": "number", "required": False, "note": "in league currency"},
        "currency": {"type": "str", "note": "default 'JOD'"},
        "registration_start": {"type": "datetime", "required": False},
        "registration_end": {"type": "datetime", "required": False},
        "rules_text": {"type": "str", "required": False},
        "organizer_id": {"type": "str", "ref": "users._id"},
        "is_active": {"type": "bool", "note": "default True"},
        "deleted_at": {"type": "datetime", "required": False},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

SEASONS_SCHEMA = _shape(
    "A season/edition of a league. Only one is_current per league.",
    ["league_id", "name"],
    {
        "_id": {"type": "str"},
        "league_id": {"type": "str", "ref": "leagues._id"},
        "name": {"type": "str", "note": "e.g. '2026/2027'"},
        "year_start": {"type": "int", "required": False},
        "year_end": {"type": "int", "required": False},
        "status": {"type": "str", "enum": "LEAGUE_STATUS", "note": "default DRAFT"},
        "start_date": {"type": "datetime", "required": False},
        "end_date": {"type": "datetime", "required": False},
        "is_current": {"type": "bool", "note": "default False; at most one True per league"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

DIVISIONS_SCHEMA = _shape(
    "Tier/division within a league season (optional; single-division "
    "leagues can skip this).",
    ["league_id", "season_id", "name", "level"],
    {
        "_id": {"type": "str"},
        "league_id": {"type": "str", "ref": "leagues._id"},
        "season_id": {"type": "str", "ref": "seasons._id"},
        "name": {"type": "str", "note": "e.g. 'Premier Division'"},
        "level": {"type": "int", "note": "1 = top tier"},
        "max_teams": {"type": "int", "required": False},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

LEAGUE_TEAMS_SCHEMA = _shape(
    "Team entry in a league season. Source of truth for participation; "
    "(league_id, season_id, team_id) unique.",
    ["league_id", "season_id", "team_id"],
    {
        "_id": {"type": "str"},
        "league_id": {"type": "str", "ref": "leagues._id"},
        "season_id": {"type": "str", "ref": "seasons._id"},
        "division_id": {"type": "str", "required": False, "ref": "divisions._id"},
        "team_id": {"type": "str", "ref": "teams._id"},
        "status": {"type": "str", "enum": "LEAGUE_TEAM_STATUS", "note": "default PENDING"},
        "payment_status": {"type": "str", "enum": "PAYMENT_STATUS", "required": False,
                           "note": "registration fee state"},
        "seed": {"type": "int", "required": False, "note": "draw seed"},
        "group": {"type": "str", "required": False, "note": "group label when league uses groups"},
        "joined_at": {"type": "datetime"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

FIXTURES_SCHEMA = _shape(
    "Schedule slot produced by the fixture generator. A match is created "
    "from a fixture when details are finalized (match.fixture_id links "
    "back). Fixtures may exist before venues/referees are assigned.",
    ["league_id", "season_id", "home_team_id", "away_team_id", "round_number"],
    {
        "_id": {"type": "str"},
        "league_id": {"type": "str", "required": False, "ref": "leagues._id",
                      "note": "None for tournament fixtures"},
        "season_id": {"type": "str", "required": False, "ref": "seasons._id"},
        "division_id": {"type": "str", "required": False, "ref": "divisions._id"},
        "tournament_id": {"type": "str", "required": False, "ref": "tournaments._id",
                          "note": "set for tournament fixtures; mutually exclusive with league_id"},
        "tournament_round_id": {"type": "str", "required": False, "ref": "tournament_rounds._id"},
        "round_number": {"type": "int", "note": "matchday/round number"},
        "round_name": {"type": "str", "required": False, "note": "e.g. 'Matchday 3', 'Semi-final'"},
        "home_team_id": {"type": "str", "ref": "teams._id"},
        "away_team_id": {"type": "str", "ref": "teams._id"},
        "scheduled_at": {"type": "datetime", "required": False},
        "facility_id": {"type": "str", "required": False, "ref": "facilities._id"},
        "pitch_id": {"type": "str", "required": False, "ref": "pitches._id"},
        "match_id": {"type": "str", "required": False, "ref": "matches._id",
                     "note": "filled when the match record is created"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

# ---------------------------------------------------------------------------
# Matches, events, lineups, statistics
# ---------------------------------------------------------------------------

MATCHES_SCHEMA = _shape(
    "A football match. Exactly one competition context: league season OR "
    "tournament. Scores live under `score`; status follows MATCH_STATUS.",
    ["home_team_id", "away_team_id", "scheduled_at"],
    {
        "_id": {"type": "str"},
        "fixture_id": {"type": "str", "required": False, "ref": "fixtures._id"},
        "league_id": {"type": "str", "required": False, "ref": "leagues._id"},
        "season_id": {"type": "str", "required": False, "ref": "seasons._id"},
        "division_id": {"type": "str", "required": False, "ref": "divisions._id"},
        "tournament_id": {"type": "str", "required": False, "ref": "tournaments._id"},
        "tournament_round_id": {"type": "str", "required": False, "ref": "tournament_rounds._id"},
        "home_team_id": {"type": "str", "ref": "teams._id"},
        "away_team_id": {"type": "str", "ref": "teams._id"},
        "scheduled_at": {"type": "datetime"},
        "venue_name": {"type": "str", "required": False},
        "facility_id": {"type": "str", "required": False, "ref": "facilities._id"},
        "pitch_id": {"type": "str", "required": False, "ref": "pitches._id"},
        "status": {"type": "str", "enum": "MATCH_STATUS", "note": "default SCHEDULED"},
        "score": {"type": "dict", "note": "{home, away, home_ht, away_ht, home_pen, away_pen}; ints, default 0"},
        "current_minute": {"type": "int", "required": False, "note": "live score clock"},
        "winner_team_id": {"type": "str", "required": False, "ref": "teams._id",
                           "note": "set for knockout ties incl. penalty shootouts"},
        "notes": {"type": "str", "required": False},
        "result_confirmed_by": {"type": "str", "required": False, "ref": "users._id"},
        "result_confirmed_at": {"type": "datetime", "required": False},
        "is_verified": {"type": "bool", "note": "default False; admin/official verification"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

MATCH_EVENTS_SCHEMA = _shape(
    "Timeline events of a match. Append-only; IMMUTABLE once the match is "
    "FINISHED (amendments require matches.result permission and re-run "
    "stats recalc). Ordered by (match_id, minute, extra_minute, created_at).",
    ["match_id", "team_id", "type", "minute"],
    {
        "_id": {"type": "str"},
        "match_id": {"type": "str", "ref": "matches._id"},
        "team_id": {"type": "str", "ref": "teams._id"},
        "player_id": {"type": "str", "required": False, "ref": "users._id",
                      "note": "primary player (scorer, carded, subbed off)"},
        "related_player_id": {"type": "str", "required": False, "ref": "users._id",
                              "note": "assist provider / player subbed on"},
        "type": {"type": "str", "enum": "MATCH_EVENT_TYPE"},
        "minute": {"type": "int", "note": "0-120+"},
        "extra_minute": {"type": "int", "required": False, "note": "stoppage, e.g. 90+2"},
        "period": {"type": "str", "required": False, "enum": "MATCH_PERIOD"},
        "description": {"type": "str", "required": False},
        "created_by": {"type": "str", "required": False, "ref": "users._id"},
        "created_at": {"type": "datetime"},
    },
)

MATCH_LINEUPS_SCHEMA = _shape(
    "Lineup per team per match. (match_id, team_id) unique.",
    ["match_id", "team_id", "formation", "starters"],
    {
        "_id": {"type": "str"},
        "match_id": {"type": "str", "ref": "matches._id"},
        "team_id": {"type": "str", "ref": "teams._id"},
        "formation": {"type": "str", "note": "e.g. '4-4-2'"},
        "starters": {"type": "list", "note": "[{player_id, jersey_number, position, is_captain}]"},
        "substitutes": {"type": "list", "note": "same shape as starters"},
        "coach_name": {"type": "str", "required": False},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

PLAYER_STATISTICS_SCHEMA = _shape(
    "DERIVED aggregate per player per competition scope. Written only by "
    "the stats recalc service from FINISHED matches — never from user input.",
    ["player_id", "scope"],
    {
        "_id": {"type": "str"},
        "player_id": {"type": "str", "ref": "users._id"},
        "scope": {"type": "dict", "note": "{league_id?, season_id?, tournament_id?} — exactly one competition context"},
        "matches_played": {"type": "int", "note": "default 0"},
        "starts": {"type": "int", "note": "default 0"},
        "minutes_played": {"type": "int", "note": "default 0"},
        "goals": {"type": "int", "note": "default 0"},
        "assists": {"type": "int", "note": "default 0"},
        "yellow_cards": {"type": "int", "note": "default 0"},
        "red_cards": {"type": "int", "note": "default 0"},
        "clean_sheets": {"type": "int", "note": "default 0 (GK/defenders)"},
        "updated_at": {"type": "datetime"},
    },
)

TEAM_STATISTICS_SCHEMA = _shape(
    "DERIVED aggregate per team per competition scope. Written only by "
    "the stats recalc service from FINISHED matches.",
    ["team_id", "scope"],
    {
        "_id": {"type": "str"},
        "team_id": {"type": "str", "ref": "teams._id"},
        "scope": {"type": "dict", "note": "{league_id?, season_id?, tournament_id?}"},
        "matches_played": {"type": "int", "note": "default 0"},
        "won": {"type": "int", "note": "default 0"},
        "drawn": {"type": "int", "note": "default 0"},
        "lost": {"type": "int", "note": "default 0"},
        "goals_for": {"type": "int", "note": "default 0"},
        "goals_against": {"type": "int", "note": "default 0"},
        "clean_sheets": {"type": "int", "note": "default 0"},
        "updated_at": {"type": "datetime"},
    },
)

STANDINGS_SCHEMA = _shape(
    "DERIVED league table. One row per (league, season, division/group, "
    "team). Recalculated from FINISHED matches only; rows exist only for "
    "APPROVED league_teams entries.",
    ["league_id", "season_id", "team_id", "points"],
    {
        "_id": {"type": "str"},
        "league_id": {"type": "str", "ref": "leagues._id"},
        "season_id": {"type": "str", "ref": "seasons._id"},
        "division_id": {"type": "str", "required": False, "ref": "divisions._id"},
        "group": {"type": "str", "required": False, "note": "group label when league uses groups"},
        "team_id": {"type": "str", "ref": "teams._id"},
        "played": {"type": "int", "note": "default 0"},
        "won": {"type": "int", "note": "default 0"},
        "drawn": {"type": "int", "note": "default 0"},
        "lost": {"type": "int", "note": "default 0"},
        "goals_for": {"type": "int", "note": "default 0"},
        "goals_against": {"type": "int", "note": "default 0"},
        "goal_difference": {"type": "int", "note": "default 0"},
        "points": {"type": "int", "note": "default 0"},
        "form": {"type": "list", "note": "last-5 results, e.g. ['W','D','L','W','W']"},
        "position": {"type": "int", "required": False, "note": "rank after sort"},
        "updated_at": {"type": "datetime"},
    },
)

# ---------------------------------------------------------------------------
# Tournaments
# ---------------------------------------------------------------------------

TOURNAMENTS_SCHEMA = _shape(
    "Knockout / round-robin / groups+knockout competitions.",
    ["name", "slug", "format", "organizer_id"],
    {
        "_id": {"type": "str"},
        "name": {"type": "str"},
        "name_ar": {"type": "str", "required": False},
        "slug": {"type": "str", "note": "globally unique"},
        "description": {"type": "str", "required": False},
        "logo_url": {"type": "str", "required": False},
        "format": {"type": "str", "enum": "TOURNAMENT_FORMAT"},
        "status": {"type": "str", "enum": "LEAGUE_STATUS", "note": "default DRAFT"},
        "max_teams": {"type": "int", "required": False},
        "num_groups": {"type": "int", "required": False, "note": "for GROUPS_KNOCKOUT"},
        "teams_advancing_per_group": {"type": "int", "required": False},
        "entry_fee": {"type": "number", "required": False},
        "currency": {"type": "str", "note": "default 'JOD'"},
        "prize_info": {"type": "str", "required": False},
        "governorate_key": {"type": "str", "required": False, "ref": "governorates.key"},
        "registration_start": {"type": "datetime", "required": False},
        "registration_end": {"type": "datetime", "required": False},
        "start_date": {"type": "datetime", "required": False},
        "end_date": {"type": "datetime", "required": False},
        "organizer_id": {"type": "str", "ref": "users._id"},
        "is_active": {"type": "bool", "note": "default True"},
        "deleted_at": {"type": "datetime", "required": False},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

TOURNAMENT_GROUPS_SCHEMA = _shape(
    "Groups within a GROUPS_KNOCKOUT tournament. (tournament_id, name) unique.",
    ["tournament_id", "name"],
    {
        "_id": {"type": "str"},
        "tournament_id": {"type": "str", "ref": "tournaments._id"},
        "name": {"type": "str", "note": "e.g. 'Group A'"},
        "order": {"type": "int", "note": "display order"},
        "created_at": {"type": "datetime"},
    },
)

TOURNAMENT_ROUNDS_SCHEMA = _shape(
    "Knockout rounds (or group-stage round labels) of a tournament.",
    ["tournament_id", "name", "stage_order"],
    {
        "_id": {"type": "str"},
        "tournament_id": {"type": "str", "ref": "tournaments._id"},
        "name": {"type": "str", "note": "e.g. 'Round of 16', 'Quarter-final', 'Semi-final', 'Final'"},
        "stage_order": {"type": "int", "note": "1 = earliest"},
        "is_knockout": {"type": "bool", "note": "default True"},
        "leg": {"type": "int", "required": False, "note": "1|2 for two-legged ties"},
        "created_at": {"type": "datetime"},
    },
)

TOURNAMENT_ENTRIES_SCHEMA = _shape(
    "Team entry in a tournament. (tournament_id, team_id) unique.",
    ["tournament_id", "team_id"],
    {
        "_id": {"type": "str"},
        "tournament_id": {"type": "str", "ref": "tournaments._id"},
        "team_id": {"type": "str", "ref": "teams._id"},
        "group_id": {"type": "str", "required": False, "ref": "tournament_groups._id"},
        "status": {"type": "str", "enum": "LEAGUE_TEAM_STATUS", "note": "default PENDING"},
        "payment_status": {"type": "str", "enum": "PAYMENT_STATUS", "required": False},
        "seed": {"type": "int", "required": False},
        "joined_at": {"type": "datetime"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

# ---------------------------------------------------------------------------
# Officiating & disputes
# ---------------------------------------------------------------------------

DISPUTES_SCHEMA = _shape(
    "Protests/disputes raised by users (match results, bookings, payments, "
    "conduct). Match disputes only within the protest window (see settings).",
    ["type", "raised_by", "title", "description"],
    {
        "_id": {"type": "str"},
        "type": {"type": "str", "enum": "DISPUTE_TYPE"},
        "status": {"type": "str", "enum": "DISPUTE_STATUS", "note": "default OPEN"},
        "raised_by": {"type": "str", "ref": "users._id"},
        "match_id": {"type": "str", "required": False, "ref": "matches._id"},
        "booking_id": {"type": "str", "required": False, "ref": "bookings._id"},
        "league_id": {"type": "str", "required": False, "ref": "leagues._id"},
        "tournament_id": {"type": "str", "required": False, "ref": "tournaments._id"},
        "title": {"type": "str"},
        "description": {"type": "str"},
        "evidence_urls": {"type": "list", "required": False, "note": "uploads paths/URLs"},
        "assigned_to": {"type": "str", "required": False, "ref": "users._id",
                        "note": "admin handling the case"},
        "resolution_notes": {"type": "str", "required": False},
        "resolved_at": {"type": "datetime", "required": False},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

REFEREES_SCHEMA = _shape(
    "Referee directory. May or may not be linked to a platform user.",
    ["name"],
    {
        "_id": {"type": "str"},
        "user_id": {"type": "str", "required": False, "ref": "users._id",
                    "note": "unique when set"},
        "name": {"type": "str"},
        "name_ar": {"type": "str", "required": False},
        "license_number": {"type": "str", "required": False, "note": "unique when set"},
        "level": {"type": "str", "required": False, "note": "e.g. 'FIFA', 'National', 'Regional', 'Grassroots'"},
        "governorate_key": {"type": "str", "required": False, "ref": "governorates.key"},
        "phone": {"type": "str", "required": False},
        "photo_url": {"type": "str", "required": False},
        "is_active": {"type": "bool", "note": "default True"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

REFEREE_ASSIGNMENTS_SCHEMA = _shape(
    "Referee assigned to a match in a role. (match_id, referee_id, role) "
    "unique. Frozen once the match is FINISHED.",
    ["match_id", "referee_id", "role", "assigned_by"],
    {
        "_id": {"type": "str"},
        "match_id": {"type": "str", "ref": "matches._id"},
        "referee_id": {"type": "str", "ref": "referees._id"},
        "role": {"type": "str", "enum": "REFEREE_ASSIGNMENT_ROLE"},
        "status": {"type": "str", "enum": "REFEREE_ASSIGNMENT_STATUS", "note": "default ASSIGNED"},
        "assigned_by": {"type": "str", "ref": "users._id"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

# ---------------------------------------------------------------------------
# Content & messaging
# ---------------------------------------------------------------------------

NEWS_SCHEMA = _shape(
    "News articles (Arabic + English). Slug unique; soft-deleted via status.",
    ["title", "slug", "body"],
    {
        "_id": {"type": "str"},
        "title": {"type": "str"},
        "title_ar": {"type": "str", "required": False},
        "slug": {"type": "str", "note": "globally unique"},
        "excerpt": {"type": "str", "required": False},
        "body": {"type": "str", "note": "markdown/html"},
        "body_ar": {"type": "str", "required": False},
        "cover_url": {"type": "str", "required": False},
        "category": {"type": "str", "required": False,
                     "note": "e.g. 'league', 'tournament', 'transfer', 'general'"},
        "tags": {"type": "list", "required": False},
        "league_id": {"type": "str", "required": False, "ref": "leagues._id"},
        "tournament_id": {"type": "str", "required": False, "ref": "tournaments._id"},
        "author_id": {"type": "str", "required": False, "ref": "users._id"},
        "status": {"type": "str", "enum": "CONTENT_STATUS", "note": "default DRAFT"},
        "is_featured": {"type": "bool", "note": "default False"},
        "view_count": {"type": "int", "note": "default 0"},
        "published_at": {"type": "datetime", "required": False},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

ANNOUNCEMENTS_SCHEMA = _shape(
    "Platform-wide or scoped announcements (banners/alerts).",
    ["title", "body", "created_by"],
    {
        "_id": {"type": "str"},
        "title": {"type": "str"},
        "title_ar": {"type": "str", "required": False},
        "body": {"type": "str"},
        "body_ar": {"type": "str", "required": False},
        "audience": {"type": "str", "note": "ALL | PLAYERS | OWNERS | ADMINS | REFEREES; "
                                            "or 'LEAGUE:<league_id>' / 'TOURNAMENT:<tournament_id>'"},
        "league_id": {"type": "str", "required": False, "ref": "leagues._id"},
        "tournament_id": {"type": "str", "required": False, "ref": "tournaments._id"},
        "priority": {"type": "str", "note": "LOW | NORMAL | HIGH | URGENT; default NORMAL"},
        "status": {"type": "str", "enum": "CONTENT_STATUS", "note": "default DRAFT"},
        "published_at": {"type": "datetime", "required": False},
        "expires_at": {"type": "datetime", "required": False},
        "created_by": {"type": "str", "ref": "users._id"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

PUSH_SUBSCRIPTIONS_SCHEMA = _shape(
    "Web-push subscriptions. (user_id, endpoint) unique — re-subscribing "
    "updates the row, never duplicates it.",
    ["user_id", "endpoint", "keys"],
    {
        "_id": {"type": "str"},
        "user_id": {"type": "str", "ref": "users._id"},
        "endpoint": {"type": "str", "note": "push service URL"},
        "keys": {"type": "dict", "note": "{p256dh, auth} — VAPID keys, secret; never log"},
        "user_agent": {"type": "str", "required": False},
        "is_active": {"type": "bool", "note": "default True; False on 410 Gone"},
        "last_used_at": {"type": "datetime", "required": False},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

NOTIFICATION_PREFERENCES_SCHEMA = _shape(
    "Per-user notification preferences. user_id unique (upsert).",
    ["user_id"],
    {
        "_id": {"type": "str"},
        "user_id": {"type": "str", "ref": "users._id", "note": "unique"},
        "channels": {"type": "dict", "note": "{push: bool, email: bool, sms: bool}; defaults all True"},
        "categories": {"type": "dict", "required": False,
                       "note": "e.g. {match_reminders: bool, team_invites: bool, league_news: bool, "
                               "booking_updates: bool, dispute_updates: bool}"},
        "quiet_hours_start": {"type": "int", "required": False, "note": "hour 0-23, local"},
        "quiet_hours_end": {"type": "int", "required": False, "note": "hour 0-23, local"},
        "created_at": {"type": "datetime"},
        "updated_at": {"type": "datetime"},
    },
)

SETTINGS_SCHEMA = _shape(
    "Platform key-value settings. _id IS the setting key; upsert by key.",
    ["value"],
    {
        "_id": {"type": "str", "note": "the setting key itself, e.g. 'site_name', 'match_protest_window_hours'"},
        "value": {"type": "any", "note": "JSON-serializable"},
        "value_type": {"type": "str", "note": "string | number | boolean | json"},
        "description": {"type": "str", "required": False},
        "updated_by": {"type": "str", "required": False, "ref": "users._id"},
        "updated_at": {"type": "datetime"},
    },
)

# Registry of schema docs for all Phase-2 collections, keyed by collection name.
SCHEMAS = {
    "governorates": GOVERNORATES_SCHEMA,
    "cities": CITIES_SCHEMA,
    "areas": AREAS_SCHEMA,
    "teams": TEAMS_SCHEMA,
    "team_members": TEAM_MEMBERS_SCHEMA,
    "team_invitations": TEAM_INVITATIONS_SCHEMA,
    "player_profiles": PLAYER_PROFILES_SCHEMA,
    "leagues": LEAGUES_SCHEMA,
    "seasons": SEASONS_SCHEMA,
    "divisions": DIVISIONS_SCHEMA,
    "league_teams": LEAGUE_TEAMS_SCHEMA,
    "fixtures": FIXTURES_SCHEMA,
    "matches": MATCHES_SCHEMA,
    "match_events": MATCH_EVENTS_SCHEMA,
    "match_lineups": MATCH_LINEUPS_SCHEMA,
    "player_statistics": PLAYER_STATISTICS_SCHEMA,
    "team_statistics": TEAM_STATISTICS_SCHEMA,
    "standings": STANDINGS_SCHEMA,
    "tournaments": TOURNAMENTS_SCHEMA,
    "tournament_groups": TOURNAMENT_GROUPS_SCHEMA,
    "tournament_rounds": TOURNAMENT_ROUNDS_SCHEMA,
    "tournament_entries": TOURNAMENT_ENTRIES_SCHEMA,
    "disputes": DISPUTES_SCHEMA,
    "referees": REFEREES_SCHEMA,
    "referee_assignments": REFEREE_ASSIGNMENTS_SCHEMA,
    "news": NEWS_SCHEMA,
    "announcements": ANNOUNCEMENTS_SCHEMA,
    "push_subscriptions": PUSH_SUBSCRIPTIONS_SCHEMA,
    "notification_preferences": NOTIFICATION_PREFERENCES_SCHEMA,
    "settings": SETTINGS_SCHEMA,
}
